language: c++
services:
  - docker
env:
  - POKY=yocto-2.6.1
addons:
  apt:
    packages:
      - s3cmd
before_install:
  - docker pull crops/poky
script:
  - docker run --rm -it -v $PWD:/workdir -e AWS_BUCKET=$AWS_BUCKET -e POKY=$POKY crops/poky --workdir=/workdir --cmd scripts/travis-build.sh
  # Copy new sstate files to S3 bucket.
  - export SSTATE_CACHE=$TRAVIS_BUILD_DIR/build/sstate-cache
  - $TRAVIS_BUILD_DIR/scripts/sstate2s3.sh
  # Summarize results and set final job result.
  - echo "TravisCI result $TRAVIS_TEST_RESULT, build result ${BITBAKE_RESULT:-0}, test result ${TEST_RESULT:-0}"; if [ $TRAVIS_TEST_RESULT -eq 0 ] && ( [ "$BITBAKE_RESULT" ] || [ "$TEST_RESULT" ] ); then TRAVIS_TEST_RESULT=1; false; fi
